version: '3'

services:
  redis:
    image: redis:alpine

  processor:
    build:
      context: ./processor/
      dockerfile: Dockerfile
    command: flask run -h 0.0.0.0
    ports:
      - '5001:5000'
    
    depends_on:
      - 'redis'


